/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteRouteImport } from './routes/_layout/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InvitationsIndexRouteImport } from './routes/invitations/index'
import { Route as InvitationsDeclineRouteImport } from './routes/invitations/decline'
import { Route as InvitationsAcceptRouteImport } from './routes/invitations/accept'
import { Route as LayoutSettingsIndexRouteImport } from './routes/_layout/settings/index'
import { Route as LayoutGroceriesIndexRouteImport } from './routes/_layout/groceries/index'
import { Route as ApiZeroMutateRouteImport } from './routes/api/zero/mutate'
import { Route as ApiPushSplatRouteImport } from './routes/api/push/$'
import { Route as ApiInvitationsSplatRouteImport } from './routes/api/invitations/$'
import { Route as ApiAuthRefreshRouteImport } from './routes/api/auth/refresh'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as LayoutGroceriesShoppingIndexRouteImport } from './routes/_layout/groceries/shopping/index'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRouteRoute = LayoutRouteRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationsIndexRoute = InvitationsIndexRouteImport.update({
  id: '/invitations/',
  path: '/invitations/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationsDeclineRoute = InvitationsDeclineRouteImport.update({
  id: '/invitations/decline',
  path: '/invitations/decline',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationsAcceptRoute = InvitationsAcceptRouteImport.update({
  id: '/invitations/accept',
  path: '/invitations/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutSettingsIndexRoute = LayoutSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutGroceriesIndexRoute = LayoutGroceriesIndexRouteImport.update({
  id: '/groceries/',
  path: '/groceries/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const ApiZeroMutateRoute = ApiZeroMutateRouteImport.update({
  id: '/api/zero/mutate',
  path: '/api/zero/mutate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushSplatRoute = ApiPushSplatRouteImport.update({
  id: '/api/push/$',
  path: '/api/push/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInvitationsSplatRoute = ApiInvitationsSplatRouteImport.update({
  id: '/api/invitations/$',
  path: '/api/invitations/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRefreshRoute = ApiAuthRefreshRouteImport.update({
  id: '/api/auth/refresh',
  path: '/api/auth/refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutGroceriesShoppingIndexRoute =
  LayoutGroceriesShoppingIndexRouteImport.update({
    id: '/groceries/shopping/',
    path: '/groceries/shopping/',
    getParentRoute: () => LayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/invitations/decline': typeof InvitationsDeclineRoute
  '/invitations': typeof InvitationsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/refresh': typeof ApiAuthRefreshRoute
  '/api/invitations/$': typeof ApiInvitationsSplatRoute
  '/api/push/$': typeof ApiPushSplatRoute
  '/api/zero/mutate': typeof ApiZeroMutateRoute
  '/groceries': typeof LayoutGroceriesIndexRoute
  '/settings': typeof LayoutSettingsIndexRoute
  '/groceries/shopping': typeof LayoutGroceriesShoppingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/invitations/decline': typeof InvitationsDeclineRoute
  '/invitations': typeof InvitationsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/refresh': typeof ApiAuthRefreshRoute
  '/api/invitations/$': typeof ApiInvitationsSplatRoute
  '/api/push/$': typeof ApiPushSplatRoute
  '/api/zero/mutate': typeof ApiZeroMutateRoute
  '/groceries': typeof LayoutGroceriesIndexRoute
  '/settings': typeof LayoutSettingsIndexRoute
  '/groceries/shopping': typeof LayoutGroceriesShoppingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/invitations/decline': typeof InvitationsDeclineRoute
  '/invitations/': typeof InvitationsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/refresh': typeof ApiAuthRefreshRoute
  '/api/invitations/$': typeof ApiInvitationsSplatRoute
  '/api/push/$': typeof ApiPushSplatRoute
  '/api/zero/mutate': typeof ApiZeroMutateRoute
  '/_layout/groceries/': typeof LayoutGroceriesIndexRoute
  '/_layout/settings/': typeof LayoutSettingsIndexRoute
  '/_layout/groceries/shopping/': typeof LayoutGroceriesShoppingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/invitations/accept'
    | '/invitations/decline'
    | '/invitations'
    | '/api/auth/$'
    | '/api/auth/refresh'
    | '/api/invitations/$'
    | '/api/push/$'
    | '/api/zero/mutate'
    | '/groceries'
    | '/settings'
    | '/groceries/shopping'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/invitations/accept'
    | '/invitations/decline'
    | '/invitations'
    | '/api/auth/$'
    | '/api/auth/refresh'
    | '/api/invitations/$'
    | '/api/push/$'
    | '/api/zero/mutate'
    | '/groceries'
    | '/settings'
    | '/groceries/shopping'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/invitations/accept'
    | '/invitations/decline'
    | '/invitations/'
    | '/api/auth/$'
    | '/api/auth/refresh'
    | '/api/invitations/$'
    | '/api/push/$'
    | '/api/zero/mutate'
    | '/_layout/groceries/'
    | '/_layout/settings/'
    | '/_layout/groceries/shopping/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRouteRoute: typeof LayoutRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  InvitationsAcceptRoute: typeof InvitationsAcceptRoute
  InvitationsDeclineRoute: typeof InvitationsDeclineRoute
  InvitationsIndexRoute: typeof InvitationsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAuthRefreshRoute: typeof ApiAuthRefreshRoute
  ApiInvitationsSplatRoute: typeof ApiInvitationsSplatRoute
  ApiPushSplatRoute: typeof ApiPushSplatRoute
  ApiZeroMutateRoute: typeof ApiZeroMutateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations/': {
      id: '/invitations/'
      path: '/invitations'
      fullPath: '/invitations'
      preLoaderRoute: typeof InvitationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations/decline': {
      id: '/invitations/decline'
      path: '/invitations/decline'
      fullPath: '/invitations/decline'
      preLoaderRoute: typeof InvitationsDeclineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations/accept': {
      id: '/invitations/accept'
      path: '/invitations/accept'
      fullPath: '/invitations/accept'
      preLoaderRoute: typeof InvitationsAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/settings/': {
      id: '/_layout/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/groceries/': {
      id: '/_layout/groceries/'
      path: '/groceries'
      fullPath: '/groceries'
      preLoaderRoute: typeof LayoutGroceriesIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/api/zero/mutate': {
      id: '/api/zero/mutate'
      path: '/api/zero/mutate'
      fullPath: '/api/zero/mutate'
      preLoaderRoute: typeof ApiZeroMutateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/$': {
      id: '/api/push/$'
      path: '/api/push/$'
      fullPath: '/api/push/$'
      preLoaderRoute: typeof ApiPushSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/invitations/$': {
      id: '/api/invitations/$'
      path: '/api/invitations/$'
      fullPath: '/api/invitations/$'
      preLoaderRoute: typeof ApiInvitationsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/refresh': {
      id: '/api/auth/refresh'
      path: '/api/auth/refresh'
      fullPath: '/api/auth/refresh'
      preLoaderRoute: typeof ApiAuthRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/groceries/shopping/': {
      id: '/_layout/groceries/shopping/'
      path: '/groceries/shopping'
      fullPath: '/groceries/shopping'
      preLoaderRoute: typeof LayoutGroceriesShoppingIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
  }
}

interface LayoutRouteRouteChildren {
  LayoutGroceriesIndexRoute: typeof LayoutGroceriesIndexRoute
  LayoutSettingsIndexRoute: typeof LayoutSettingsIndexRoute
  LayoutGroceriesShoppingIndexRoute: typeof LayoutGroceriesShoppingIndexRoute
}

const LayoutRouteRouteChildren: LayoutRouteRouteChildren = {
  LayoutGroceriesIndexRoute: LayoutGroceriesIndexRoute,
  LayoutSettingsIndexRoute: LayoutSettingsIndexRoute,
  LayoutGroceriesShoppingIndexRoute: LayoutGroceriesShoppingIndexRoute,
}

const LayoutRouteRouteWithChildren = LayoutRouteRoute._addFileChildren(
  LayoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRouteRoute: LayoutRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  InvitationsAcceptRoute: InvitationsAcceptRoute,
  InvitationsDeclineRoute: InvitationsDeclineRoute,
  InvitationsIndexRoute: InvitationsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAuthRefreshRoute: ApiAuthRefreshRoute,
  ApiInvitationsSplatRoute: ApiInvitationsSplatRoute,
  ApiPushSplatRoute: ApiPushSplatRoute,
  ApiZeroMutateRoute: ApiZeroMutateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
