/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvitationsRouteImport } from './routes/invitations'
import { Route as LayoutRouteRouteImport } from './routes/_layout/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutSettingsIndexRouteImport } from './routes/_layout/settings/index'
import { Route as LayoutGroceriesIndexRouteImport } from './routes/_layout/groceries/index'
import { Route as LayoutGroceriesShoppingIndexRouteImport } from './routes/_layout/groceries/shopping/index'
import { ServerRoute as ApiZeroMutateServerRouteImport } from './routes/api/zero/mutate'
import { ServerRoute as ApiPushSplatServerRouteImport } from './routes/api/push/$'
import { ServerRoute as ApiInvitationsSplatServerRouteImport } from './routes/api/invitations/$'
import { ServerRoute as ApiAuthRefreshServerRouteImport } from './routes/api/auth/refresh'
import { ServerRoute as ApiAuthSplatServerRouteImport } from './routes/api/auth/$'

const rootServerRouteImport = createServerRootRoute()

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationsRoute = InvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRouteRoute = LayoutRouteRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutSettingsIndexRoute = LayoutSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutGroceriesIndexRoute = LayoutGroceriesIndexRouteImport.update({
  id: '/groceries/',
  path: '/groceries/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutGroceriesShoppingIndexRoute =
  LayoutGroceriesShoppingIndexRouteImport.update({
    id: '/groceries/shopping/',
    path: '/groceries/shopping/',
    getParentRoute: () => LayoutRouteRoute,
  } as any)
const ApiZeroMutateServerRoute = ApiZeroMutateServerRouteImport.update({
  id: '/api/zero/mutate',
  path: '/api/zero/mutate',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiPushSplatServerRoute = ApiPushSplatServerRouteImport.update({
  id: '/api/push/$',
  path: '/api/push/$',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiInvitationsSplatServerRoute =
  ApiInvitationsSplatServerRouteImport.update({
    id: '/api/invitations/$',
    path: '/api/invitations/$',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiAuthRefreshServerRoute = ApiAuthRefreshServerRouteImport.update({
  id: '/api/auth/refresh',
  path: '/api/auth/refresh',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiAuthSplatServerRoute = ApiAuthSplatServerRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/invitations': typeof InvitationsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/groceries': typeof LayoutGroceriesIndexRoute
  '/settings': typeof LayoutSettingsIndexRoute
  '/groceries/shopping': typeof LayoutGroceriesShoppingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/invitations': typeof InvitationsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/groceries': typeof LayoutGroceriesIndexRoute
  '/settings': typeof LayoutSettingsIndexRoute
  '/groceries/shopping': typeof LayoutGroceriesShoppingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteRouteWithChildren
  '/invitations': typeof InvitationsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_layout/groceries/': typeof LayoutGroceriesIndexRoute
  '/_layout/settings/': typeof LayoutSettingsIndexRoute
  '/_layout/groceries/shopping/': typeof LayoutGroceriesShoppingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/invitations'
    | '/login'
    | '/register'
    | '/groceries'
    | '/settings'
    | '/groceries/shopping'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/invitations'
    | '/login'
    | '/register'
    | '/groceries'
    | '/settings'
    | '/groceries/shopping'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/invitations'
    | '/login'
    | '/register'
    | '/_layout/groceries/'
    | '/_layout/settings/'
    | '/_layout/groceries/shopping/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRouteRoute: typeof LayoutRouteRouteWithChildren
  InvitationsRoute: typeof InvitationsRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}
export interface FileServerRoutesByFullPath {
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/auth/refresh': typeof ApiAuthRefreshServerRoute
  '/api/invitations/$': typeof ApiInvitationsSplatServerRoute
  '/api/push/$': typeof ApiPushSplatServerRoute
  '/api/zero/mutate': typeof ApiZeroMutateServerRoute
}
export interface FileServerRoutesByTo {
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/auth/refresh': typeof ApiAuthRefreshServerRoute
  '/api/invitations/$': typeof ApiInvitationsSplatServerRoute
  '/api/push/$': typeof ApiPushSplatServerRoute
  '/api/zero/mutate': typeof ApiZeroMutateServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/auth/refresh': typeof ApiAuthRefreshServerRoute
  '/api/invitations/$': typeof ApiInvitationsSplatServerRoute
  '/api/push/$': typeof ApiPushSplatServerRoute
  '/api/zero/mutate': typeof ApiZeroMutateServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths:
    | '/api/auth/$'
    | '/api/auth/refresh'
    | '/api/invitations/$'
    | '/api/push/$'
    | '/api/zero/mutate'
  fileServerRoutesByTo: FileServerRoutesByTo
  to:
    | '/api/auth/$'
    | '/api/auth/refresh'
    | '/api/invitations/$'
    | '/api/push/$'
    | '/api/zero/mutate'
  id:
    | '__root__'
    | '/api/auth/$'
    | '/api/auth/refresh'
    | '/api/invitations/$'
    | '/api/push/$'
    | '/api/zero/mutate'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiAuthSplatServerRoute: typeof ApiAuthSplatServerRoute
  ApiAuthRefreshServerRoute: typeof ApiAuthRefreshServerRoute
  ApiInvitationsSplatServerRoute: typeof ApiInvitationsSplatServerRoute
  ApiPushSplatServerRoute: typeof ApiPushSplatServerRoute
  ApiZeroMutateServerRoute: typeof ApiZeroMutateServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations': {
      id: '/invitations'
      path: '/invitations'
      fullPath: '/invitations'
      preLoaderRoute: typeof InvitationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/settings/': {
      id: '/_layout/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/groceries/': {
      id: '/_layout/groceries/'
      path: '/groceries'
      fullPath: '/groceries'
      preLoaderRoute: typeof LayoutGroceriesIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/groceries/shopping/': {
      id: '/_layout/groceries/shopping/'
      path: '/groceries/shopping'
      fullPath: '/groceries/shopping'
      preLoaderRoute: typeof LayoutGroceriesShoppingIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/zero/mutate': {
      id: '/api/zero/mutate'
      path: '/api/zero/mutate'
      fullPath: '/api/zero/mutate'
      preLoaderRoute: typeof ApiZeroMutateServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/push/$': {
      id: '/api/push/$'
      path: '/api/push/$'
      fullPath: '/api/push/$'
      preLoaderRoute: typeof ApiPushSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/invitations/$': {
      id: '/api/invitations/$'
      path: '/api/invitations/$'
      fullPath: '/api/invitations/$'
      preLoaderRoute: typeof ApiInvitationsSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/auth/refresh': {
      id: '/api/auth/refresh'
      path: '/api/auth/refresh'
      fullPath: '/api/auth/refresh'
      preLoaderRoute: typeof ApiAuthRefreshServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface LayoutRouteRouteChildren {
  LayoutGroceriesIndexRoute: typeof LayoutGroceriesIndexRoute
  LayoutSettingsIndexRoute: typeof LayoutSettingsIndexRoute
  LayoutGroceriesShoppingIndexRoute: typeof LayoutGroceriesShoppingIndexRoute
}

const LayoutRouteRouteChildren: LayoutRouteRouteChildren = {
  LayoutGroceriesIndexRoute: LayoutGroceriesIndexRoute,
  LayoutSettingsIndexRoute: LayoutSettingsIndexRoute,
  LayoutGroceriesShoppingIndexRoute: LayoutGroceriesShoppingIndexRoute,
}

const LayoutRouteRouteWithChildren = LayoutRouteRoute._addFileChildren(
  LayoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRouteRoute: LayoutRouteRouteWithChildren,
  InvitationsRoute: InvitationsRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiAuthSplatServerRoute: ApiAuthSplatServerRoute,
  ApiAuthRefreshServerRoute: ApiAuthRefreshServerRoute,
  ApiInvitationsSplatServerRoute: ApiInvitationsSplatServerRoute,
  ApiPushSplatServerRoute: ApiPushSplatServerRoute,
  ApiZeroMutateServerRoute: ApiZeroMutateServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
